### ISSUE TITLE
Support armv7

### ISSUE THREAD

**Issue by ferjm** [Igalia/wpe-android#10] opened 2021-05-11 15:38 UTC
All dependencies can be cross-compiled to armv7 except for WPEWebKit.

The current link error is:

```
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/MediaTime.cpp.o):MediaTime.cpp:function WTF::MediaTime::setTimeScale(unsigned int, WTF::MediaTime::RoundingFlags): error: undefined reference to '__mulodi4'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/MediaTime.cpp.o):MediaTime.cpp:function WTF::MediaTime::operator*(int) const: error: undefined reference to '__mulodi4'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/MediaTime.cpp.o):MediaTime.cpp:function WTF::MediaTime::operator*(int) const: error: undefined reference to '__mulodi4'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/MediaTime.cpp.o):MediaTime.cpp:function WTF::MediaTime::compare(WTF::MediaTime const&) const: error: undefined reference to '__mulodi4'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

I see the same issue building for android_x86

**Comment by blino** [comment] 2021-06-09 13:27
This should have been fixed in WPE 2.32, see https://bugs.webkit.org/show_bug.cgi?id=190208

The current Cerbero package is using 2.30.4, right?

**Comment by aperezdc** [comment] 2022-03-28 23:17
I have a [WIP branch for ARMv7 support](https://github.com/Igalia/cerbero/tree/aperezdc/armv7) and probably it will be ready for review soon. I can confirm that the WebKit build issue is not present anymore in newer releases (tested with 2.34.x).

**Comment by aperezdc** [comment] 2022-03-30 11:21
Using https://github.com/Igalia/cerbero/pull/12 in combination with the changes in commit https://github.com/Igalia/wpe-android/commit/dea3ff68c30738f21a099a437fc9bea224e51245 I have been able to build what seems to be correct ARMv7 packages.

The `.apk` resulting from running `./gradlew assembleMinApi26Debug -Parch=armv7` installed fine in an old 32-bit device which I had around, running LineageOS 15.1 (Oreo 8.1, API level 27), but then when starting the Minibrowser there is a backtrace from what I believe might be incorrect usage of the API compatbility libraries (probably worth a separate bug report).

**Comment by mariospr** [comment] 2022-05-12 17:37
@aperezdc As per comment https://github.com/Igalia/wpe-android/issues/10#issuecomment-1083005419 (and the landed commits) it seems that this particular issue might have been already fixed.

If that's the case, please feel free to move it to "Done" and close it, thanks!

**Comment by aperezdc** [comment] 2022-05-19 22:28
ARMv7 builds work, I just think nobody got to have the Minibrowser running on actual hardware. When I tried running it on an older ARMv7 phone I got stuck due to issue #60, but I think we can close this issue anyway.

**Closed by aperezdc** 2022-05-19 22:28 UTC
Labels: bug, priority-low
